### ISSUE TITLE
How to directly output URL Encode?

### ISSUE THREAD

**Issue by kerim** [willfarrell/alfred-encode-decode-workflow#10]
I'm working on an Alfred Workflow where I need high ASCII characters encoded for a URL. I was able to import your workflow into my own and incorporate it, but the output is something like this (for the input "#text":

```
<?xml version="1.0"?>
<items><item uid="URL Encoded" arg="%23text" valid="yes" autocomplete=""><title>%23text</title><subtitle>URL Encoded</subtitle><icon>icon.png</icon></item><item uid="base64 Encoded" arg="I3RleHQ=" valid="yes" autocomplete=""><title>I3RleHQ=</title><subtitle>base64 Encoded</subtitle><icon>icon.png</icon></item></items>
```

How can I modify it so I only get the URL encoded text as output?

Thanks!

**Comment by willfarrell** [comment]
You're better off looking at the source code and duplicating in in yours. In php it's `urlencode($str)`, that's it. There typically a built in function in most languages for this operation.

**Comment by kerim** [comment]
Thanks.
