### ISSUE TITLE
Encoding issue with JSON

### ISSUE THREAD

**Issue by jesselumarie** [willfarrell/alfred-encode-decode-workflow#14]
Howdy!

I love using your workflow, and I ran into something I can't get around. When encoding the following JSON object, the second half of the object is "cut off", so to speak:

**Expected**:
`encode {"foo": 1, "bar": 2}` --> `eyJmb28iOiAxLCAiYmFyIjogMn0=` --> `decode eyJmb28iOiAxLCAiYmFyIjogMn0` --> `{"foo": 1, "bar": 2}`

**Actual**
`encode {"foo": 1, "bar": 2}` --> `ImZvbyI6IDE=` --> `decode ImZvbyI6IDE=` --> `"foo":1`

I'm on Alfred 3.7 (build 938), and using v1.8 of the workflow.

**Comment by likecreep** [comment]
Same. Alfred v3.7.1[946]

**Comment by willfarrell** [comment]
Sorry, I missed this.

I just did a test, seems to work fine for me. Pushed a new version, just in case. Please let me know if that resolves this.

**Comment by likecreep** [comment]
> Sorry, I missed this.
> 
> I just did a test, seems to work fine for me. Pushed a new version, just in case. Please let me know if that resolves this.
Hi, I just tested it with the new version but still got the same problem.
![image](https://user-images.githubusercontent.com/28685148/50300925-d4af4900-04c0-11e9-9b4e-21abdb2d9a2c.png)

**Comment by jesselumarie** [comment]
Looks like it’s working on my new Mac — thanks for the reply!

**Comment by willfarrell** [comment]
I think I figured it out. It was how Alfred was escaping the query. I push `v1.10`, please try that. hopeful I didn't break something else with this change.
