### ISSUE TITLE
Use Alfred environment variables in workflows.php

### ISSUE THREAD

**Issue by xilopaint** [willfarrell/alfred-encode-decode-workflow#15]
`workflows.php` uses Alfred 2 hardcoded paths to create data and cache folders:
https://github.com/willfarrell/alfred-encode-decode-workflow/blob/3674954be5cec8051e0b0002ae6dd434946a38e3/src/workflows.php#L41-L42
Please, consider to use [Script Environment Variables](https://www.alfredapp.com/help/workflows/script-environment-variables/) instead, so these folders won't be created at wrong locations for Alfred 3 users.

**Comment by 111andre111** [comment]
Whoever wants to fix this you could fix that on disk by finding workflow.php and then change the mentioned to lines to the following code
```
   $this->cache = getenv('alfred_workflow_cache');
   $this->data  = getenv('alfred_workflow_data');
```
