### ISSUE TITLE
支持Packal Search 

### ISSUE THREAD

**Issue by Liuruyong** [willfarrell/alfred-encode-decode-workflow#17]
可以把这个workflow上传到http://www.packal.org ，就可以在alfred通过packal search直接搜索到了。
搜索到的类似工具没有这个好用

**Comment by Liuruyong** [comment]
http://www.packal.org/workflow/packal-workflow-search

**Comment by willfarrell** [comment]
Translation: `You can upload this workflow to http://www.packal.org and you can search directly in alfred via package search. Similar tools found are not as easy to use.`

I've submitted to Packal. It should show up in the next couple of days.
