### ISSUE TITLE
Running into this when I try to trigger this workflow in mac catalina

### ISSUE THREAD

**Issue by artivilla** [willfarrell/alfred-encode-decode-workflow#21]
I installed this app and when I trigger `encode` I get the following:

![image](https://user-images.githubusercontent.com/2120159/70853520-01e8ca00-1e7d-11ea-8f61-a8dd678d5c10.png)

**Comment by kushdilip** [comment]
I may be too late but anyways

Search for "Security & Privacy" in Spotlight or Alfred or System Preferences to see below screen
![Screenshot 2020-03-23 at 10 39 03 AM](https://user-images.githubusercontent.com/1286008/77283565-adae7b00-6cf2-11ea-8b45-3cea373ce781.png)

Here you will see applications blocked by mac which you can manually click to allow opening them
