### ISSUE TITLE
macOS Monterey stop bundling PHP

### ISSUE THREAD

**Issue by tomy0000000** [willfarrell/alfred-encode-decode-workflow#23]
It is confirmed that macOS Monterey will stop provide built-in PHP, see [here](https://www.php.net/manual/en/install.macosx.bundled.php) and [there](https://developer.apple.com/forums/thread/681907).

The solution would probably be...

* Bundle php binaries in this workflow (I'm not sure if that's going to work / suitable)
* Add a user-guide to instruct user install php with homebrew (Probably the easiest, but not ideal for non-geeky users)
* Rebuild the whole functionality in another scripting language

For anyone who stumble across this, the quick solution is

1. Install PHP via homebrew

```shell
brew install php
```

2. Change php path in Alfred

Double-click on `encode` / `decode` block, and change `php` to `/usr/local/bin/php`

**Comment by willfarrell** [comment]
Would you like to put a PR to update the docs?
Setting the $PATH shouldn't require a change in Alfred, usually brew takes care of this.

**Comment by tomy0000000** [comment]
@willfarrell

I've tried fixing this issue by setting `export PATH=/usr/local/bin:$PATH` in many different ways. For instance, inside `.bashrc`, `.bash_profile`, `.profile`, `.zshrc`...etc.
The thing is, alfred execute these script in non-interactive mode, so it won't source those rcfiles implicitly.
Changing path in Alfred is the most easiest way to do, IMHO.

**Comment by willfarrell** [comment]
Thanks for checking. Let's add the docs on how to change path then. Since people will be using both versions for at least a year.
