### ISSUE TITLE
how to get encode for empty space

### ISSUE THREAD

**Issue by ZheFeng** [willfarrell/alfred-encode-decode-workflow#9]
I use empty space encode many a lot. When I try to use this workflow, I found that I can't get encode for space. How can I get the html encode for space?

I try: 
encode  
encode space
encode [space]
encode [ ]
encode {space}

**Comment by willfarrell** [comment]
So when the input matches the output is does not return a result.
As for space, we're using [htmlentities](http://php.net/manual/en/function.htmlentities.php) for the html encoding. This function does not encode ` ` to `&nbsp;` if that is what you were expecting.
